# Setup
title:        TJ's Property Management
tagline:      We develop individual solutions for you
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
